name: Update Rules
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule: 
    - cron:  '0 0 */1 * *' 

jobs:
  Pushed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.0

      - name: Commit Changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then 
              exit 0
          else 
              git add .
              git config --local user.email "hcamer145@gmail.com"
              git config --local user.name "hacamer"
              git commit -m "Updated at $(date)" -a
          fi
            
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}

      - uses: actions/checkout@main  
      - name: Git push assets to github & coding
        run: |
          rm -rf .git/
          git init
          git config --local user.name "hacamer"
          git config --local user.email "hcamer145@gmail.com"
          git branch -m main
          git add --all
          git commit -m "Updated at $(date)"
          #git remote add origin "https://github.com/Cats-Team/Ad-Rules.git"
          git remote add origin "https://${{ secrets.CODING_TokenUser }}:${{ secrets.CODING_Token }}@e.coding.net/hacamer/repos/script.git"
          #git fetch --unshallow origin
          git push -u -f origin main
          #git push -f
          #git push --set-upstream origin main
