name: Update Rules
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule: 
    - cron:  '0 0 */1 * *' 

jobs:
  Pushed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.0

      - name: CSDN-Pro
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://greasyfork.org/scripts/378351-%E6%8C%81%E7%BB%AD%E6%9B%B4%E6%96%B0-csdn%E5%B9%BF%E5%91%8A%E5%AE%8C%E5%85%A8%E8%BF%87%E6%BB%A4-%E4%BA%BA%E6%80%A7%E5%8C%96%E8%84%9A%E6%9C%AC%E4%BC%98%E5%8C%96-%E4%B8%8D%E7%94%A8%E5%86%8D%E7%99%BB%E5%BD%95%E4%BA%86-%E8%AE%A9%E4%BD%A0%E4%BD%93%E9%AA%8C%E4%BB%A4%E4%BA%BA%E6%83%8A%E5%96%9C%E7%9A%84%E5%B4%AD%E6%96%B0csdn/code/%F0%9F%94%A5%E6%8C%81%E7%BB%AD%E6%9B%B4%E6%96%B0%F0%9F%94%A5%20CSDN%E5%B9%BF%E5%91%8A%E5%AE%8C%E5%85%A8%E8%BF%87%E6%BB%A4%E3%80%81%E4%BA%BA%E6%80%A7%E5%8C%96%E8%84%9A%E6%9C%AC%E4%BC%98%E5%8C%96%EF%BC%9A%F0%9F%86%95%20%E4%B8%8D%E7%94%A8%E5%86%8D%E7%99%BB%E5%BD%95%E4%BA%86%EF%BC%81%E8%AE%A9%E4%BD%A0%E4%BD%93%E9%AA%8C%E4%BB%A4%E4%BA%BA%E6%83%8A%E5%96%9C%E7%9A%84%E5%B4%AD%E6%96%B0CSDN%E3%80%82.user.js
          file-name: csdn-pro.user.js


      - name: 知乎增强
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://greasyfork.org/scripts/419081-%E7%9F%A5%E4%B9%8E%E5%A2%9E%E5%BC%BA/code/%E7%9F%A5%E4%B9%8E%E5%A2%9E%E5%BC%BA.user.js
          file-name: zhihu-pro.user.js

      - name: 百度系去广告
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://greasyfork.org/scripts/394099-%E7%99%BE%E5%BA%A6%E7%B3%BB%E7%BD%91%E7%AB%99%E5%8E%BB%E5%B9%BF%E5%91%8A/code/%E7%99%BE%E5%BA%A6%E7%B3%BB%E7%BD%91%E7%AB%99%E5%8E%BB%E5%B9%BF%E5%91%8A.user.js
          file-name: rm-baiduad.user.js

      - name: 通用阅读器
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://greasyfork.org/scripts/377230-%E9%80%9A%E7%94%A8%E9%98%85%E8%AF%BB%E5%99%A8/code/%E9%80%9A%E7%94%A8%E9%98%85%E8%AF%BB%E5%99%A8.user.js
          file-name: yuedu-all.user.js

      - name: 谷歌翻译
        uses: carlosperate/download-file-action@v1.0.0
        with: 
          file-url: https://greasyfork.org/scripts/424966-%E7%BD%91%E9%A1%B5%E7%BF%BB%E8%AF%91-%E7%BF%BB%E8%AF%91%E4%B8%BA%E4%B8%AD%E6%96%87/code/%E7%BD%91%E9%A1%B5%E7%BF%BB%E8%AF%91%E2%80%94%E2%80%94%E7%BF%BB%E8%AF%91%E4%B8%BA%E4%B8%AD%E6%96%87.user.js
          file-name: google-fy.user.js

      - name: Commit Changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then 
              exit 0
          else 
              git add .
              git config --local user.email "hcamer145@gmail.com"
              git config --local user.name "hacamer"
              git commit -m "Updated at $(date)" -a
          fi
            
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}

      - uses: actions/checkout@main  
      - name: Git push assets to github & coding
        run: |
          rm -rf .git/
          git init
          git config --local user.name "hacamer"
          git config --local user.email "hcamer145@gmail.com"
          git branch -m main
          git add --all
          git commit -m "Updated at $(date)"
          #git remote add origin "https://github.com/Cats-Team/Ad-Rules.git"
          git remote add origin "https://${{ secrets.CODING_TokenUser }}:${{ secrets.CODING_Token }}@e.coding.net/hacamer/repos/script.git"
          #git fetch --unshallow origin
          git push -u -f origin main
          #git push -f
          #git push --set-upstream origin main
